(require 'cl)
(require 'el-mock)
(require 'undercover)
(require 'subr-x)

(setq user-home-directory (concat (getenv "HOME") "/"))

(undercover "*.el")

(add-to-list 'load-path ".")
(load "orgability.el")

(defmacro with-one-header-and-no-drawer (&rest body)
  `(with-temp-buffer
     (org-mode)
     (insert "* Some heading\n")
     (insert ":PROPERTIES:\n")
     (insert ":ID: 8366A66A-2DE6-401B-AF7F-0C03C33EA3BB\n")
     (insert ":END:\n")
     ,@body))

(defmacro with-one-header-and-empty-drawer (&rest body)
  `(with-temp-buffer
     (org-mode)
     (insert "* Some heading\n")
     (insert ":PROPERTIES:\n")
     (insert ":ID: 8366A66A-2DE6-401B-AF7F-0C03C33EA3BB\n")
     (insert ":END:\n")
     (insert ":TOPICS:\n")
     (insert ":END:\n")
     ,@body))

(defmacro with-one-header-and-drawer (&rest body)
  `(with-temp-buffer
     (org-mode)
     (insert "* Some heading\n")
     (insert ":PROPERTIES:\n")
     (insert ":ID: 8366A66A-2DE6-401B-AF7F-0C03C33EA3BB\n")
     (insert ":END:\n")
     (insert ":TOPICS:\n")
     (insert "- topic1\n")
     (insert "- topic2\n")
     (insert ":END:\n")
     ,@body))

(defmacro with-two-headers-and-no-drawer (&rest body)
  `(with-temp-buffer
     (org-mode)
     (insert "* Some heading\n")
     (insert ":PROPERTIES:\n")
     (insert ":ID: 8366A66A-2DE6-401B-AF7F-0C03C33EA3BB\n")
     (insert ":END:\n")
     (insert "* Main heading\n")
     (insert ":PROPERTIES:\n")
     (insert ":ID: 6845FDEF-EAB9-423D-8792-8E736DCD414D\n")
     (insert ":END:\n")
     ,@body))

(defmacro with-two-headers-and-empty-drawer (&rest body)
  `(with-temp-buffer
     (org-mode)
     (insert "* Some heading\n")
     (insert ":PROPERTIES:\n")
     (insert ":ID: 8366A66A-2DE6-401B-AF7F-0C03C33EA3BB\n")
     (insert ":END:\n")
     (insert "* Main heading\n")
     (insert ":PROPERTIES:\n")
     (insert ":ID: 6845FDEF-EAB9-423D-8792-8E736DCD414D\n")
     (insert ":END:\n")
     (insert ":TOPICS:\n")
     (insert ":END:\n")
     ,@body))

(defmacro with-two-headers-and-drawer (&rest body)
  `(with-temp-buffer
     (org-mode)
     (insert "* Some heading\n")
     (insert ":PROPERTIES:\n")
     (insert ":ID: 8366A66A-2DE6-401B-AF7F-0C03C33EA3BB\n")
     (insert ":END:\n")
     (insert "* Main heading\n")
     (insert ":PROPERTIES:\n")
     (insert ":ID: 6845FDEF-EAB9-423D-8792-8E736DCD414D\n")
     (insert ":END:\n")
     (insert ":TOPICS:\n")
     (insert "- topic1\n")
     (insert "- topic2\n")
     (insert ":END:\n")
     ,@body))
